name: CI

on: [ push, pull_request ]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        php: [ 8.3 ]
        node: [ 20 ]
        dependency-version: [ prefer-stable ]

    name: PHP ${{ matrix.php }} | Node ${{ matrix.node }} | ${{ matrix.os }} | ${{ matrix.dependency-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Composer dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist

      - name: Install Node.js dependencies
        run: npm ci

      - name: Rector Cache
        uses: actions/cache@v3
        with:
          path: /tmp/rector
          key: ${{ runner.os }}-rector-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-rector-

      - name: Create Rector cache directory
        run: mkdir -p /tmp/rector

      - name: Rector Dry Run
        run: composer run rector:cache

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run migrations
        run: php artisan migrate --force

      - name: PHP Linting
        run: composer run lint

      - name: Build assets
        run: npm run build

      - name: JavaScript Linting
        run: npm run lint

      - name: Run PHP tests
        run: composer run test

      - name: Run JavaScript tests
        run: npm test
