name: CI

on: ["push", "pull_request"]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.3]
        pnpm: [8]
        dependency-version: [prefer-stable]

    name: PHP ${{ matrix.php }} | PNPM ${{ matrix.pnpm }} | OS ${{ matrix.os }} | Dependency Resolution ${{ matrix.dependency-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install Composer dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist

      - name: Install node dependencies
        run: npm ci

      - name: Rector Cache
        uses: actions/cache@v3
        with:
          path: /tmp/rector
          key: ${{ runner.os }}-rector-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-rector-

      - run: mkdir -p /tmp/rector

      - name: Rector Dry Run
        run: composer run rector:cache

      - name: Setup just
        uses: extractions/setup-just@v2

      - name: Run CI checks
        run: composer check

      - name: Copy .env
        run: cp .env.ci .env

      - name: Build assets
        run: pnpm run build

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run migrations
        run: php artisan migrate --force --seed

      - name: Run tests
        run: composer run test:integration
